environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
  - gradlew.bat --no-daemon --version
build: off
test_script:
  # install and build source
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache build
  # test embedded tomcat
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache tomcatInstall
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache tomcatStart
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache tomcatStop
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache tomcatClearLogs
  # test HSQL
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache hsqlStart
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache dataInit
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache hsqlStop
  # test skin generation tool
  - gradlew.bat -u -i -S --no-daemon --no-parallel --no-build-cache skinGenerate -DskinName=appveyor
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
